# Site settings
title: starfleetcadet75
author:
  name: starfleetcadet75
  email: starfleetcadet75@gmail.com
description: >
  Reversing, Vulnerability Research, CTFs
baseurl: ""
url: "https://starfleetcadet75.github.io"
skin: dark
markdown: kramdown
date_format: "%b %-d, %Y"
show_excerpts: true
social_links:
  #twitter: jekyllrb
  github: starfleetcadet75

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-mentions
